export const VEHICLE_COMPONENTS = [
  "FRAME",
  "FRONT_SUSPENSION",
  "REAR_SUSPENSION",
  "FRONT_WHEEL",
  "REAR_WHEEL",
  "BRAKING_SYSTEM",
  "STEERING_SYSTEM",
  "POWERTRAIN",
  "FUEL_OR_BATTERY_SYSTEM",
  "EXHAUST_OR_THERMAL_SYSTEM",
  "ELECTRICAL_SYSTEM",
  "BODYWORK",
  "SEAT",
  "LIGHTING",
  "CONTROLS"
] as const;
