/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActualizacionesRouteImport } from './routes/admin.actualizaciones'
import { Route as AdminAnaliticasRouteImport } from './routes/admin.analiticas'
import { Route as AdminPagosRouteImport } from './routes/admin.pagos'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminSuscripcionesRouteImport } from './routes/admin.suscripciones'
import { Route as AdminTalleresRouteImport } from './routes/admin.talleres'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppDiagnosticoRouteImport } from './routes/app.diagnostico'
import { Route as AppIngenieriaRouteImport } from './routes/app.ingenieria'
import { Route as AppOrdenesRouteImport } from './routes/app.ordenes'
import { Route as AppPiezasRouteImport } from './routes/app.piezas'
import { Route as AppVehiculosRouteImport } from './routes/app.vehiculos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActualizacionesRoute = AdminActualizacionesRouteImport.update({
  id: '/actualizaciones',
  path: '/actualizaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnaliticasRoute = AdminAnaliticasRouteImport.update({
  id: '/analiticas',
  path: '/analiticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuscripcionesRoute = AdminSuscripcionesRouteImport.update({
  id: '/suscripciones',
  path: '/suscripciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTalleresRoute = AdminTalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticoRoute = AppDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AppRoute,
} as any)
const AppIngenieriaRoute = AppIngenieriaRouteImport.update({
  id: '/ingenieria',
  path: '/ingenieria',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdenesRoute = AppOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => AppRoute,
} as any)
const AppPiezasRoute = AppPiezasRouteImport.update({
  id: '/piezas',
  path: '/piezas',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiculosRoute = AppVehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/actualizaciones': typeof AdminActualizacionesRoute
  '/admin/analiticas': typeof AdminAnaliticasRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/ingenieria': typeof AppIngenieriaRoute
  '/app/ordenes': typeof AppOrdenesRoute
  '/app/piezas': typeof AppPiezasRoute
  '/app/vehiculos': typeof AppVehiculosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/actualizaciones': typeof AdminActualizacionesRoute
  '/admin/analiticas': typeof AdminAnaliticasRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/ingenieria': typeof AppIngenieriaRoute
  '/app/ordenes': typeof AppOrdenesRoute
  '/app/piezas': typeof AppPiezasRoute
  '/app/vehiculos': typeof AppVehiculosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/actualizaciones': typeof AdminActualizacionesRoute
  '/admin/analiticas': typeof AdminAnaliticasRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/ingenieria': typeof AppIngenieriaRoute
  '/app/ordenes': typeof AppOrdenesRoute
  '/app/piezas': typeof AppPiezasRoute
  '/app/vehiculos': typeof AppVehiculosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/actualizaciones'
    | '/admin/analiticas'
    | '/admin/pagos'
    | '/admin/productos'
    | '/admin/suscripciones'
    | '/admin/talleres'
    | '/app/analytics'
    | '/app/clientes'
    | '/app/diagnostico'
    | '/app/ingenieria'
    | '/app/ordenes'
    | '/app/piezas'
    | '/app/vehiculos'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/actualizaciones'
    | '/admin/analiticas'
    | '/admin/pagos'
    | '/admin/productos'
    | '/admin/suscripciones'
    | '/admin/talleres'
    | '/app/analytics'
    | '/app/clientes'
    | '/app/diagnostico'
    | '/app/ingenieria'
    | '/app/ordenes'
    | '/app/piezas'
    | '/app/vehiculos'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/actualizaciones'
    | '/admin/analiticas'
    | '/admin/pagos'
    | '/admin/productos'
    | '/admin/suscripciones'
    | '/admin/talleres'
    | '/app/analytics'
    | '/app/clientes'
    | '/app/diagnostico'
    | '/app/ingenieria'
    | '/app/ordenes'
    | '/app/piezas'
    | '/app/vehiculos'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actualizaciones': {
      id: '/admin/actualizaciones'
      path: '/actualizaciones'
      fullPath: '/admin/actualizaciones'
      preLoaderRoute: typeof AdminActualizacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analiticas': {
      id: '/admin/analiticas'
      path: '/analiticas'
      fullPath: '/admin/analiticas'
      preLoaderRoute: typeof AdminAnaliticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suscripciones': {
      id: '/admin/suscripciones'
      path: '/suscripciones'
      fullPath: '/admin/suscripciones'
      preLoaderRoute: typeof AdminSuscripcionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/talleres': {
      id: '/admin/talleres'
      path: '/talleres'
      fullPath: '/admin/talleres'
      preLoaderRoute: typeof AdminTalleresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostico': {
      id: '/app/diagnostico'
      path: '/diagnostico'
      fullPath: '/app/diagnostico'
      preLoaderRoute: typeof AppDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ingenieria': {
      id: '/app/ingenieria'
      path: '/ingenieria'
      fullPath: '/app/ingenieria'
      preLoaderRoute: typeof AppIngenieriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ordenes': {
      id: '/app/ordenes'
      path: '/ordenes'
      fullPath: '/app/ordenes'
      preLoaderRoute: typeof AppOrdenesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/piezas': {
      id: '/app/piezas'
      path: '/piezas'
      fullPath: '/app/piezas'
      preLoaderRoute: typeof AppPiezasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vehiculos': {
      id: '/app/vehiculos'
      path: '/vehiculos'
      fullPath: '/app/vehiculos'
      preLoaderRoute: typeof AppVehiculosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActualizacionesRoute: typeof AdminActualizacionesRoute
  AdminAnaliticasRoute: typeof AdminAnaliticasRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminSuscripcionesRoute: typeof AdminSuscripcionesRoute
  AdminTalleresRoute: typeof AdminTalleresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActualizacionesRoute: AdminActualizacionesRoute,
  AdminAnaliticasRoute: AdminAnaliticasRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminSuscripcionesRoute: AdminSuscripcionesRoute,
  AdminTalleresRoute: AdminTalleresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppClientesRoute: typeof AppClientesRoute
  AppDiagnosticoRoute: typeof AppDiagnosticoRoute
  AppIngenieriaRoute: typeof AppIngenieriaRoute
  AppOrdenesRoute: typeof AppOrdenesRoute
  AppPiezasRoute: typeof AppPiezasRoute
  AppVehiculosRoute: typeof AppVehiculosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppClientesRoute: AppClientesRoute,
  AppDiagnosticoRoute: AppDiagnosticoRoute,
  AppIngenieriaRoute: AppIngenieriaRoute,
  AppOrdenesRoute: AppOrdenesRoute,
  AppPiezasRoute: AppPiezasRoute,
  AppVehiculosRoute: AppVehiculosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
